apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: transportdash
  labels:
    group: db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: transportdash
  labels:
    group: db
type: Opaque
data:
  POSTGRES_DB: YWlyZmxvdw== # Base64 encoded value of "airflow"
  POSTGRES_USER: YWlyZmxvdw== # Base64 encoded value of "airflow"
  POSTGRES_PASSWORD: YWlyZmxvdw== # Base64 encoded value of "airflow"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: transportdash
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: ""
  AIRFLOW__API__SECRET_KEY: "supersecretkey"
  AIRFLOW_CONN_POSTGRES_CONN: postgresql://airflow:airflow@postgres:5432/airflow
  AIRFLOW__API_AUTH__JWT_SECRET: "superdupersecretkey"
data:
  AIS_API_KEY: OWFkYmQ5NjQ2NzRkMjJiYTUyOWUxMzg2YWFjY2NlYzc2NDUyYzM2Yg== # Base64 encoded value
---
apiVersion: v1
kind: Secret
metadata:
  name: streamlit-secret
  namespace: transportdash
type: Opaque
stringData:
  POSTGRES_SERVICE_HOST: "postgres"
  POSTGRES_SERVICE_PORT: "5432"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  namespace: transportdash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: transportdash
  labels:
    app: postgres
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        type: db
    spec:
      volumes: # indicates which PVC are available for this Deployment
        - name: "postgres-storage"
          persistentVolumeClaim:
            claimName: pg-pv-claim
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts: # indicates which Volume (from spec.template.spec.volumes) should be used
            - name: postgres-storage # name of the Volume
              mountPath: /var/lib/postgresql/data # path inside the container
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: transportdash
  labels:
    app: streamlit
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: transportdash
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      enableServiceLinks: false
      containers:
        - name: streamlit
          image: transportdash-streamlit:fix7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
              value: "false"
            - name: STREAMLIT_SERVER_RUN_ON_SAVE
              value: "true"
            - name: STREAMLIT_SERVER_ADDRESS
              value: "0.0.0.0"
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: STREAMLIT_THEME_BASE
              value: "dark"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: streamlit-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: transportdash
  labels:
    app: airflow-webserver
spec:
  type: ClusterIP
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: transportdash
  labels:
    app: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: transportdash-airflow:fix7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS
              value: "True"
            - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
              value: airflow.utils.net.get_host_ip_address
            - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT
              value: "8793"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: "http://airflow-webserver:8080/execution/"
          envFrom:
            - secretRef:
                name: airflow-secret
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db migrate &&
              exec airflow api-server
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: transportdash
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: transportdash-airflow:fix7
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
              value: airflow.utils.net.get_host_ip_address
            - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT
              value: "8793"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: "http://airflow-webserver:8080/execution/"
          envFrom:
            - secretRef:
                name: airflow-secret
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db migrate &&
              exec airflow scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dagprocessor
  namespace: transportdash
  labels:
    app: airflow-dagprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-dagprocessor
  template:
    metadata:
      labels:
        app: airflow-dagprocessor
    spec:
      containers:
        - name: airflow-dagprocessor
          image: transportdash-airflow:fix7
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
              value: airflow.utils.net.get_host_ip_address
            - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT
              value: "8793"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: "http://airflow-webserver:8080/execution/"
          envFrom:
            - secretRef:
                name: airflow-secret
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db migrate &&
              exec airflow dag-processor